#undef RGB_DISABLE_TIMEOUT
#define RGB_DISABLE_TIMEOUT 60000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define FIRMWARE_VERSION u8"QqBOp/JEnyO"
#define RGB_MATRIX_STARTUP_SPD 60

#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_TERM 210
#define PERMISSIVE_HOLD
